#!/usr/bin/env python3
"""Render `Formula/brake.rb` from the release checksums.

Kept as a script rather than inlined in YAML because the formula is the thing a
`brew install` actually executes: it deserves to be readable, diffable and
runnable on its own. `python3 .github/render-formula.py` with `VERSION` and
`CHECKSUMS` set reproduces exactly what the release job commits.

`CHECKSUMS` is the JSON the release job emits: target triple -> sha256 of the
archive for that target.
"""

import json
import os
import sys

REPOSITORY = "grahambrooks/brake"

# Which archive serves which platform. `on_macos`/`on_linux` with an arch
# guard is the shape Homebrew expects, and it is why the four Mac/Linux
# combinations each need their own build.
PLATFORMS = [
    ("on_macos", "Hardware::CPU.arm?", "aarch64-apple-darwin"),
    ("on_macos", "Hardware::CPU.intel?", "x86_64-apple-darwin"),
    ("on_linux", "Hardware::CPU.arm?", "aarch64-unknown-linux-gnu"),
    ("on_linux", "Hardware::CPU.intel?", "x86_64-unknown-linux-gnu"),
]


def main() -> int:
    version = os.environ.get("VERSION", "").strip()
    if not version:
        print("VERSION is required", file=sys.stderr)
        return 2

    try:
        checksums = json.loads(os.environ.get("CHECKSUMS", "{}"))
    except json.JSONDecodeError as error:
        print(f"CHECKSUMS is not valid JSON: {error}", file=sys.stderr)
        return 2

    missing = [target for _, _, target in PLATFORMS if target not in checksums]
    if missing:
        # A formula referencing an archive that was never uploaded fails at
        # `brew install`, on someone else's machine, at the worst moment.
        print(f"no checksum for: {', '.join(missing)}", file=sys.stderr)
        return 1

    base = f"https://github.com/{REPOSITORY}/releases/download/v{version}"
    lines = [
        "# Generated by .github/render-formula.py during release. Do not edit by hand.",
        "#",
        "#   brew tap grahambrooks/brake https://github.com/grahambrooks/brake",
        "#   brew install brake",
        "class Brake < Formula",
        '  desc "A brake on breaking API changes: checks API contracts for '
        'backward compatibility"',
        f'  homepage "https://github.com/{REPOSITORY}"',
        f'  version "{version}"',
        '  license "MIT"',
        "",
    ]

    grouped: dict[str, list[tuple[str, str]]] = {}
    for section, guard, target in PLATFORMS:
        grouped.setdefault(section, []).append((guard, target))

    for section, entries in grouped.items():
        lines.append(f"  {section} do")
        for index, (guard, target) in enumerate(entries):
            keyword = "if" if index == 0 else "elsif"
            lines += [
                f"    {keyword} {guard}",
                f'      url "{base}/brake-v{version}-{target}.tar.gz"',
                f'      sha256 "{checksums[target]}"',
            ]
        lines += ["    end", "  end", ""]

    lines += [
        "  def install",
        '    bin.install "brake"',
        "  end",
        "",
        "  test do",
        # Not just `--version`: that would pass on a binary that cannot do
        # anything. `explain` exercises the rule catalogue, which is the thing
        # every finding depends on.
        '    assert_match version.to_s, shell_output("#{bin}/brake --version")',
        '    assert_match "deprecate-then-remove",',
        '                 shell_output("#{bin}/brake explain response-field-removed")',
        "  end",
        "end",
    ]

    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
