# Generated by .github/render-formula.py during release. Do not edit by hand.
#
#   brew tap grahambrooks/brake https://github.com/grahambrooks/brake
#   brew install brake
class Brake < Formula
  desc "A brake on breaking API changes: checks API contracts for backward compatibility"
  homepage "https://github.com/grahambrooks/brake"
  version "2026.8.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/brake/archive/refs/tags/v2026.9.1.tar.gz"
      sha256 "5656a06240fe0ae626ec4f7470549d209dbfa942f434cfdb2df5588629929825"
    elsif Hardware::CPU.intel?
      url "https://github.com/grahambrooks/brake/releases/download/v2026.8.4/brake-v2026.8.4-x86_64-apple-darwin.tar.gz"
      sha256 "54bb95b968fd64fa2cd7cf1255b46fb29444730b501db7a1aea2a223493a93a5"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/brake/releases/download/v2026.8.4/brake-v2026.8.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "82de81f1abea32449798e3929ab4f3da95b826a87bd143a1829d86fd969a0e43"
    elsif Hardware::CPU.intel?
      url "https://github.com/grahambrooks/brake/releases/download/v2026.8.4/brake-v2026.8.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "99ed156581b597bea352eaaaf804684352ee249419309005858e9730890bc924"
    end
  end

  def install
    bin.install "brake"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/brake --version")
    assert_match "deprecate-then-remove",
                 shell_output("#{bin}/brake explain response-field-removed")
  end
end
