# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Brake < Formula
  desc "A brake on breaking API changes: checks API contracts for backward compatibility"
  homepage "https://github.com/grahambrooks/brake"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/brake/releases/download/v2026.10.1/brake-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "4c47dd101457a16ce34700b78645114aa9b0c741d10c431856b11bfff87299f4"
    end
    on_intel do
      url "https://github.com/grahambrooks/brake/releases/download/v2026.10.1/brake-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "58d716ef045c3c6ea97aaa5c9461df2a14187463dc41cbd4d0c6ff4239811100"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/brake/releases/download/v2026.10.1/brake-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cc8983aaf29de804906904446e68c2b7304bd79eb99e42754d56aa7e57a78f1d"
    end
    on_intel do
      url "https://github.com/grahambrooks/brake/releases/download/v2026.10.1/brake-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "35719d77277695a0903361454e4979c0e997029aba13e121cc5f9edf8a9d6432"
    end
  end

  def install
    bin.install "brake"
  end

  test do
    assert_path_exists bin/"brake"
  end
end
